
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Damien
 */
public class LaFenetre extends javax.swing.JFrame {
    private Conteneur<String,Personnel> leConteneur;
    private boolean creer = true;

    public LaFenetre(Conteneur<String,Personnel> leConteneur)
    {
        this.leConteneur=leConteneur;
        initComponents();
        
        
    }
    /**
     * Creates new form LaFenetre
     */
    public LaFenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEmpCom = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btDébut = new javax.swing.JButton();
        btSuivant = new javax.swing.JButton();
        btPrecedent = new javax.swing.JButton();
        btFin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbNumEtu = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtMatricule = new javax.swing.JTextField();
        lbNom = new javax.swing.JLabel();
        lbTelephone = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbEmploye = new javax.swing.JRadioButton();
        rbCommercial = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        lbTaux = new javax.swing.JLabel();
        lbNbHeure = new javax.swing.JLabel();
        txtTaux = new javax.swing.JTextField();
        txtNbHeure = new javax.swing.JTextField();
        lbVentes = new javax.swing.JLabel();
        lbPourcentages = new javax.swing.JLabel();
        txtVentes = new javax.swing.JTextField();
        txtPourcentages = new javax.swing.JTextField();
        lbMontant = new javax.swing.JLabel();
        txtMontant = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btChercher = new javax.swing.JButton();
        btCreer = new javax.swing.JButton();
        btSupprimer = new javax.swing.JButton();
        lbNbObjetPresent = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        miCharger = new javax.swing.JMenuItem();
        jMenuSauvegarder = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miQuitter = new javax.swing.JMenuItem();
        mnInterrogation = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Personnel");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation"));

        btDébut.setText("Début");
        btDébut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDébutActionPerformed(evt);
            }
        });

        btSuivant.setText(">>");
        btSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuivantActionPerformed(evt);
            }
        });

        btPrecedent.setText("<<");
        btPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrecedentActionPerformed(evt);
            }
        });

        btFin.setText("Fin");
        btFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(btDébut)
                .add(64, 64, 64)
                .add(btPrecedent)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btSuivant)
                .add(64, 64, 64)
                .add(btFin)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btDébut)
                    .add(btSuivant)
                    .add(btPrecedent)
                    .add(btFin))
                .add(26, 26, 26))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Générales"));

        lbNumEtu.setText("Matricule");

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });

        txtMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculeActionPerformed(evt);
            }
        });

        lbNom.setText("Nom");

        lbTelephone.setText("Telephone");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbNom)
                    .add(lbTelephone))
                .add(23, 23, 23)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(txtTelephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(29, 29, 29)
                        .add(lbNumEtu)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(txtMatricule, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(txtNom))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtNom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbNom))
                .add(34, 34, 34)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtTelephone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbTelephone)
                    .add(lbNumEtu)
                    .add(txtMatricule, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Type de personnel"));

        bgEmpCom.add(rbEmploye);
        rbEmploye.setSelected(true);
        rbEmploye.setText("Employé");
        rbEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmployeActionPerformed(evt);
            }
        });

        bgEmpCom.add(rbCommercial);
        rbCommercial.setText("Commercial");
        rbCommercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCommercialActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(46, 46, 46)
                .add(rbEmploye)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(rbCommercial)
                .add(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rbEmploye)
                    .add(rbCommercial))
                .add(0, 7, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Information pour le calcul de rémunération"));

        lbTaux.setText("Taux horaire");

        lbNbHeure.setText("Nombre d'Heures");

        txtTaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTauxActionPerformed(evt);
            }
        });

        lbVentes.setText("Ventes");

        lbPourcentages.setText("Poucentages");

        lbMontant.setText("Montant brut");

        txtMontant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontantActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbNbHeure)
                    .add(lbTaux))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(lbMontant)
                        .add(42, 42, 42)
                        .add(txtMontant))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtTaux, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .add(txtNbHeure))
                        .add(52, 52, 52)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbPourcentages)
                            .add(lbVentes))))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtVentes)
                    .add(txtPourcentages))
                .add(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbTaux)
                    .add(txtTaux, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbVentes)
                    .add(txtVentes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbNbHeure)
                    .add(txtNbHeure, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbPourcentages)
                    .add(txtPourcentages, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbMontant)
                    .add(txtMontant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion du conteneur"));

        btChercher.setText("Chercher");
        btChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChercherActionPerformed(evt);
            }
        });

        btCreer.setText("Creer");
        btCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreerActionPerformed(evt);
            }
        });

        btSupprimer.setText("Supprimer");
        btSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerActionPerformed(evt);
            }
        });

        lbNbObjetPresent.setText("Nombre d'objet présent dans le conteneur : "+ leConteneur.nbElements());

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btChercher)
                .add(30, 30, 30)
                .add(btCreer)
                .add(30, 30, 30)
                .add(btSupprimer)
                .add(53, 53, 53))
            .add(jPanel5Layout.createSequentialGroup()
                .add(78, 78, 78)
                .add(lbNbObjetPresent)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btChercher)
                    .add(btCreer)
                    .add(btSupprimer))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(lbNbObjetPresent)
                .addContainerGap())
        );

        mnFile.setText("File");

        miCharger.setText("Charger");
        miCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miChargerActionPerformed(evt);
            }
        });
        mnFile.add(miCharger);

        jMenuSauvegarder.setText("Sauvegarder");
        jMenuSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSauvegarderActionPerformed(evt);
            }
        });
        mnFile.add(jMenuSauvegarder);
        mnFile.add(jSeparator1);

        miQuitter.setText("Quitter");
        miQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuitterActionPerformed(evt);
            }
        });
        mnFile.add(miQuitter);

        jMenuBar1.add(mnFile);

        mnInterrogation.setText("?");
        jMenuBar1.add(mnInterrogation);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void afficher(Personnel p)
    {
        txtMatricule.setText(p.getNumPers());
        txtTelephone.setText(p.getNumTel());
        txtNom.setText(p.getNomPers());
        if(p instanceof Commercial){
            rbCommercial.isSelected();
            txtVentes.setText(String.valueOf(((Commercial) p).getVentes()));
            txtPourcentages.setText(String.valueOf(((Commercial) p).getPourcentage()));
            txtMontant.setText(String.valueOf(((Commercial) p).getVentes()+((Commercial) p).getPourcentage()));
        }
        else {
            rbEmploye.isSelected();
            txtTaux.setText(String.valueOf(((Employe) p).getTauxHoraire()));
            txtNbHeure.setText(String.valueOf(((Employe) p).getNbHeures()));
            txtMontant.setText(String.valueOf(((Employe) p).getTauxHoraire()+((Employe) p).getNbHeures()));
        }
            
    }
    
    private void quitter()
    {
        int reponse=JOptionPane.showConfirmDialog(this,"Voulez vous quitter l'application","Attention",JOptionPane.YES_NO_CANCEL_OPTION);
        if(reponse==JOptionPane.YES_OPTION){
            System.exit(0); }
    }
    
    private void ajouter(){
        
        if (rbEmploye.isSelected()==true){
            try {
                Employe a= new Employe(txtNom.getText(),txtTelephone.getText(), Integer.parseInt(txtTaux.getText()), Integer.parseInt(txtNbHeure.getText()));
                leConteneur.ajouter(a.getNumPers(), a);
                leConteneur.sauvegarder("test.txt");
            }
            catch (Exception ex) {
            Logger.getLogger(LaFenetre.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                Commercial a=new Commercial(txtNom.getText(),txtTelephone.getText(),Integer.parseInt(txtVentes.getText()), Integer.parseInt(txtPourcentages.getText()));
                leConteneur.ajouter(a.getNumPers(), a);
                leConteneur.sauvegarder("test.txt");
            }
            catch (Exception ex) {
            Logger.getLogger(LaFenetre.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        lbNbObjetPresent.setText("Nombre d'objet présent dans le conteneur : "+ leConteneur.nbElements());
}
    
    private void boutonEmploye(){
        txtVentes.setText(null);
        txtPourcentages.setText(null);
        txtVentes.setEditable(false);
        txtPourcentages.setEditable(false);
        txtMontant.setEditable(false);
        txtTaux.setEditable(true);
        txtNbHeure.setEditable(true);
    }
    
    
    private void btSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuivantActionPerformed
        if(!leConteneur.estVide())
        {
        txtVentes.setEditable(false);
        txtPourcentages.setEditable(false);
        txtMontant.setEditable(false);
        txtTaux.setEditable(false);
        txtNbHeure.setEditable(false);    
        leConteneur.suivant();
        txtVentes.setText(""); 
        txtPourcentages.setText("");
        txtMontant.setText("");
        txtTaux.setText("");
        txtNbHeure.setText("");     
        afficher(leConteneur.obtenir(leConteneur.cleCourante()));
        }
    }//GEN-LAST:event_btSuivantActionPerformed

    private void btPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrecedentActionPerformed
        if(!leConteneur.estVide())
            
        {
        txtVentes.setEditable(false);
        txtPourcentages.setEditable(false);
        txtMontant.setEditable(false);
        txtTaux.setEditable(false);
        txtNbHeure.setEditable(false); 
        leConteneur.precedent();
        txtVentes.setText("");
        txtPourcentages.setText("");
        txtMontant.setText("");
        txtTaux.setText("");
        txtNbHeure.setText("");        
        afficher(leConteneur.obtenir(leConteneur.cleCourante()));
        }
    }//GEN-LAST:event_btPrecedentActionPerformed

    private void btDébutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDébutActionPerformed
        if(!leConteneur.estVide())
        {
            txtVentes.setEditable(false);
            txtPourcentages.setEditable(false);
            txtMontant.setEditable(false);
            txtTaux.setEditable(false);
            txtNbHeure.setEditable(false); 
            leConteneur.premier();
            txtVentes.setText("");
            txtPourcentages.setText("");
             txtMontant.setText("");
             txtTaux.setText("");
             txtNbHeure.setText("");     
             afficher(leConteneur.obtenir(leConteneur.cleCourante()));
        }
    }//GEN-LAST:event_btDébutActionPerformed

    private void btFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinActionPerformed
        if(!leConteneur.estVide())
        {
        txtVentes.setEditable(false);
        txtPourcentages.setEditable(false);
        txtMontant.setEditable(false);
        txtTaux.setEditable(false);
        txtNbHeure.setEditable(false); 
        txtVentes.setText("");
        txtPourcentages.setText("");
        txtMontant.setText("");
        txtTaux.setText("");
        txtNbHeure.setText("");     
        leConteneur.dernier();
       afficher(leConteneur.obtenir(leConteneur.cleCourante()));
        }
    }//GEN-LAST:event_btFinActionPerformed

    private void txtMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculeActionPerformed

        
    }//GEN-LAST:event_txtMatriculeActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void btCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreerActionPerformed
        
        if(creer == true){
            rbEmploye.doClick();
            txtMatricule.setEditable(false);
            txtMatricule.setText(null);
            txtTelephone.setText(null);
            txtNom.setText(null);
            txtVentes.setText(null);
            txtPourcentages.setText(null);    
            txtTaux.setText(null);
            txtNbHeure.setText(null);
            txtMontant.setText(null);
            btCreer.setText("Ok");
            creer = false;
        }
        else if(creer == false){
            ajouter();
            btCreer.setText("Creer");
            creer = true;         
        }
            
            
    }//GEN-LAST:event_btCreerActionPerformed

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerActionPerformed
        
        String cle=null;
        if(leConteneur.cleSuivante() != null){
            cle =leConteneur.cleSuivante();
            supprimer(leConteneur.cleCourante());
            leConteneur.positionner(cle);
            afficher(leConteneur.obtenir(cle));
        }
        else if(leConteneur.clePrecedente()!=null)
        {
            cle =leConteneur.clePrecedente();
            supprimer(leConteneur.cleCourante());
            leConteneur.positionner(cle);
            afficher(leConteneur.obtenir(cle));
        }
        else{
        supprimer(leConteneur.cleCourante());
        txtVentes.setText("");
        txtPourcentages.setText("");
        txtMontant.setText("");
        txtTaux.setText("");
        txtNbHeure.setText(""); 
        txtMatricule.setText("");
        txtTelephone.setText("");
        txtNom.setText("");
        
        }
      
       
        
    }//GEN-LAST:event_btSupprimerActionPerformed
    void supprimer(String cle)
    {
        leConteneur.supprimer(cle);
        
        
        lbNbObjetPresent.setText("Nombre d'objet présent dans le conteneur : "+ leConteneur.nbElements());
        try {
            leConteneur.sauvegarder("test.txt");
        } catch (Exception ex) {
            Logger.getLogger(LaFenetre.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    private void txtMontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontantActionPerformed

    private void miChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miChargerActionPerformed
        try {
            leConteneur.charger("test.txt");
        } catch (Exception ex) {

            System.out.println(ex.getMessage());
        }
        lbNbObjetPresent.setText("Nombre d'objet présent dans le conteneur : "+ leConteneur.nbElements());
    }//GEN-LAST:event_miChargerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void miQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuitterActionPerformed
        quitter();        
    }//GEN-LAST:event_miQuitterActionPerformed

    private void rbEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmployeActionPerformed

            boutonEmploye();
    }//GEN-LAST:event_rbEmployeActionPerformed

    private void rbCommercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCommercialActionPerformed

            txtTaux.setText(null);
            txtNbHeure.setText(null);
            txtTaux.setEditable(false);
            txtNbHeure.setEditable(false);
            txtMontant.setEnabled(false);
            txtVentes.setEditable(true);
            txtPourcentages.setEditable(true);            

    }//GEN-LAST:event_rbCommercialActionPerformed

    private void txtTauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTauxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTauxActionPerformed
    private String chercher(String cle)
    {
        int test;
        leConteneur.premier();
          while(leConteneur.cleCourante()!=leConteneur.cleMax())
          {
              
              if((test=cle.compareTo(leConteneur.cleCourante()))==0)
                  return leConteneur.cleCourante();
              leConteneur.cleSuivante();
              
          }
          return leConteneur.cleMin();
    }
    private void btChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChercherActionPerformed
        String reponse = JOptionPane.showInputDialog(this,"Entrez le matricule que vous cherchez \n attention, si la cle n'est pas présente, vous serez positionner au début");
        int calcul=1000+Integer.valueOf(reponse);
        String temp = "M"+Integer.toString(calcul);
        temp=chercher(temp);
        leConteneur.positionner(temp);
        afficher(leConteneur.obtenir(leConteneur.cleCourante()));
    }//GEN-LAST:event_btChercherActionPerformed

    private void jMenuSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSauvegarderActionPerformed
        try {
            leConteneur.sauvegarder("test.txt");
        } catch (Exception ex) {
            Logger.getLogger(LaFenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuSauvegarderActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaFenetre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEmpCom;
    private javax.swing.JButton btChercher;
    private javax.swing.JButton btCreer;
    private javax.swing.JButton btDébut;
    private javax.swing.JButton btFin;
    private javax.swing.JButton btPrecedent;
    private javax.swing.JButton btSuivant;
    private javax.swing.JButton btSupprimer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuSauvegarder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbMontant;
    private javax.swing.JLabel lbNbHeure;
    private javax.swing.JLabel lbNbObjetPresent;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbNumEtu;
    private javax.swing.JLabel lbPourcentages;
    private javax.swing.JLabel lbTaux;
    private javax.swing.JLabel lbTelephone;
    private javax.swing.JLabel lbVentes;
    private javax.swing.JMenuItem miCharger;
    private javax.swing.JMenuItem miQuitter;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnInterrogation;
    private javax.swing.JRadioButton rbCommercial;
    private javax.swing.JRadioButton rbEmploye;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JTextField txtMontant;
    private javax.swing.JTextField txtNbHeure;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPourcentages;
    private javax.swing.JTextField txtTaux;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVentes;
    // End of variables declaration//GEN-END:variables
}
